name: Build Plugin

on:
  push:
    branches:
      - main  # 기본 브랜치 이름에 맞게 수정하세요.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'  # 원하는 Java 버전으로 변경하세요.

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
